/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { routerCompletionsCreate3 } from "../funcs/routerCompletionsCreate3.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Completions extends ClientSDK {
  /**
   * legacy completions route
   *
   * @remarks
   * For sending requests to legacy completion models
   */
  async create3(
    request?: operations.PostV2RouterCompletionsRequestBody | undefined,
    options?: RequestOptions,
  ): Promise<operations.PostV2RouterCompletionsResponseBody> {
    return unwrapAsync(routerCompletionsCreate3(
      this,
      request,
      options,
    ));
  }
}
