/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsPostContacts } from "../funcs/contactsPostContacts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * Update user information
   *
   * @remarks
   * Update or add user information to workspace
   */
  async postContacts(
    request: operations.PostContactsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostContactsResponseBody> {
    return unwrapAsync(contactsPostContacts(
      this,
      request,
      options,
    ));
  }
}
