/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsCreate3 } from "../funcs/contactsCreate3.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * Update user information
   *
   * @remarks
   * Update or add user information to workspace
   */
  async create3(
    request: operations.CreateContactRequestBody,
    options?: RequestOptions,
  ): Promise<operations.CreateContactResponseBody> {
    return unwrapAsync(contactsCreate3(
      this,
      request,
      options,
    ));
  }
}
