/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsCreate } from "../funcs/contactsCreate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * Update user information
   *
   * @remarks
   * Update or add user information to workspace
   */
  async create(
    request: operations.PostV2ContactsRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostV2ContactsResponseBody> {
    return unwrapAsync(contactsCreate(
      this,
      request,
      options,
    ));
  }
}
