/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deploymentsGetV2Deployments } from "../funcs/deploymentsGetV2Deployments.js";
import {
  deploymentsInvoke,
  InvokeAcceptEnum,
} from "../funcs/deploymentsInvoke.js";
import { deploymentsPostV2DeploymentsGetConfig } from "../funcs/deploymentsPostV2DeploymentsGetConfig.js";
import { deploymentsPostV2DeploymentsIdMetrics } from "../funcs/deploymentsPostV2DeploymentsIdMetrics.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { InvokeAcceptEnum } from "../funcs/deploymentsInvoke.js";

export class Deployments extends ClientSDK {
  /**
   * Get config
   *
   * @remarks
   * Retrieve the deployment configuration
   */
  async postV2DeploymentsGetConfig(
    request: operations.PostV2DeploymentsGetConfigRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostV2DeploymentsGetConfigResponseBody | undefined> {
    return unwrapAsync(deploymentsPostV2DeploymentsGetConfig(
      this,
      request,
      options,
    ));
  }

  /**
   * Invoke
   *
   * @remarks
   * Invoke a deployment with a given payload
   */
  async invoke(
    request: components.Deployments,
    options?: RequestOptions & { acceptHeaderOverride?: InvokeAcceptEnum },
  ): Promise<operations.PostV2DeploymentsInvokeResponse | undefined> {
    return unwrapAsync(deploymentsInvoke(
      this,
      request,
      options,
    ));
  }

  /**
   * Add metrics
   *
   * @remarks
   * Add metrics to a deployment
   */
  async postV2DeploymentsIdMetrics(
    request: operations.PostV2DeploymentsIdMetricsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostV2DeploymentsIdMetricsResponseBody> {
    return unwrapAsync(deploymentsPostV2DeploymentsIdMetrics(
      this,
      request,
      options,
    ));
  }

  /**
   * List all deployments
   *
   * @remarks
   * Returns a list of your deployments. The deployments are returned sorted by creation date, with the most recent deployments appearing first.
   */
  async getV2Deployments(
    request: operations.GetV2DeploymentsRequest,
    options?: RequestOptions,
  ): Promise<operations.GetV2DeploymentsResponseBody> {
    return unwrapAsync(deploymentsGetV2Deployments(
      this,
      request,
      options,
    ));
  }
}
