/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { feedbackPostFeedback } from "../funcs/feedbackPostFeedback.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Feedback extends ClientSDK {
  /**
   * Submit feedback
   *
   * @remarks
   * Submit feedback for the LLM transaction via the API
   */
  async postFeedback(
    request: operations.PostFeedbackRequestBody,
    options?: RequestOptions,
  ): Promise<operations.PostFeedbackResponseBody> {
    return unwrapAsync(feedbackPostFeedback(
      this,
      request,
      options,
    ));
  }
}
