/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicDeleteV2DeploymentsInvalidateDeploymentId } from "../funcs/publicDeleteV2DeploymentsInvalidateDeploymentId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { unwrapAsync } from "../types/fp.js";

export class Public extends ClientSDK {
  /**
   * Invalidates cache
   *
   * @remarks
   * Explicitly invalidate a cache of a deployment
   */
  async deleteV2DeploymentsInvalidateDeploymentId(
    deploymentId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(publicDeleteV2DeploymentsInvalidateDeploymentId(
      this,
      deploymentId,
      options,
    ));
  }
}
