workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/haroldorquesta/test-orq-typescript-client/refs/heads/main/openapi.json
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-oas
    overlay:
        inputs:
            - location: https://raw.githubusercontent.com/haroldorquesta/test-orq-typescript-client/refs/heads/main/openapi-overlay.yaml
targets:
    orq:
        target: typescript
        source: orq-OAS
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: ""
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-oas-code-samples
