workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    orq:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq
    orq-prerelease:
        inputs:
            - location: ./openapi-prerelease.yaml
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-prerelease
targets:
    orq:
        target: typescript
        source: orq
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-code-samples
            blocking: false
    orq-prerelease:
        target: typescript
        source: orq-prerelease
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/orq/orq/orq-prerelease-code-samples
            blocking: false
