workflowVersion: 1.0.0
sources:
    orq-OAS:
        inputs:
            - location: https://docs.orq.ai/openapi/660fa7243ab69800258b6433
        registry:
            location: registry.speakeasyapi.dev/orq/orq/orq-oas
targets:
    orq:
        target: typescript
        source: orq-OAS
        publish:
            npm:
                token: $npm_token
