/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

export type GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest = {
  /**
   * Dataset ID
   */
  datasetId: string;
  /**
   * Dataset row ID
   */
  rowId: string;
};

/**
 * The role of the prompt message
 */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdRole = ClosedEnum<
  typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdRole
>;

export const GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType = {
  ImageUrl: "image_url",
} as const;
export type GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType = ClosedEnum<
  typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType
>;

export type GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl = {
  /**
   * The orq.ai id of the image
   */
  id?: string | undefined;
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type GetV2ResourcesDatasetsDatasetIdRowsRowId22 = {
  type: GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType;
  imageUrl: GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl;
};

export const GetV2ResourcesDatasetsDatasetIdRowsRowId2Type = {
  Text: "text",
} as const;
export type GetV2ResourcesDatasetsDatasetIdRowsRowId2Type = ClosedEnum<
  typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2Type
>;

/**
 * Text content part of a prompt message
 */
export type GetV2ResourcesDatasetsDatasetIdRowsRowId21 = {
  type: GetV2ResourcesDatasetsDatasetIdRowsRowId2Type;
  text: string;
};

export type GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2 =
  | GetV2ResourcesDatasetsDatasetIdRowsRowId21
  | GetV2ResourcesDatasetsDatasetIdRowsRowId22;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdContent =
  | string
  | Array<
    | GetV2ResourcesDatasetsDatasetIdRowsRowId21
    | GetV2ResourcesDatasetsDatasetIdRowsRowId22
  >;

export const GetV2ResourcesDatasetsDatasetIdRowsRowIdType = {
  Function: "function",
} as const;
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdType = ClosedEnum<
  typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdType
>;

export type GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: GetV2ResourcesDatasetsDatasetIdRowsRowIdType;
  function: GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction;
};

export type GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages = {
  /**
   * The role of the prompt message
   */
  role: GetV2ResourcesDatasetsDatasetIdRowsRowIdRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | GetV2ResourcesDatasetsDatasetIdRowsRowId21
      | GetV2ResourcesDatasetsDatasetIdRowsRowId22
    >;
  toolCalls?:
    | Array<GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls>
    | undefined;
};

/**
 * Returned dataset row model from the API.
 */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody = {
  id: string;
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
  /**
   * The date and time the resource was created
   */
  created?: Date | undefined;
  /**
   * The date and time the resource was last updated
   */
  updated?: Date | undefined;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dataset_id: z.string(),
    row_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "dataset_id": "datasetId",
      "row_id": "rowId",
    });
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound = {
  dataset_id: string;
  row_id: string;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest
  > = z.object({
    datasetId: z.string(),
    rowId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      rowId: "row_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdRole> = z
    .nativeEnum(GetV2ResourcesDatasetsDatasetIdRowsRowIdRole);

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdRole> =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema:
  z.ZodNativeEnum<
    typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType
  > = z.nativeEnum(GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType);

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema:
  z.ZodNativeEnum<
    typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType
  > = GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound = {
  id?: string | undefined;
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema:
  z.ZodType<GetV2ResourcesDatasetsDatasetIdRowsRowId22, z.ZodTypeDef, unknown> =
    z.object({
      type:
        GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema,
      image_url: z.lazy(() =>
        GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema
      ),
    }).transform((v) => {
      return remap$(v, {
        "image_url": "imageUrl",
      });
    });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound = {
  type: string;
  image_url: GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowId22
  > = z.object({
    type: GetV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema,
    imageUrl: z.lazy(() =>
      GetV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowId22$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound` instead. */
  export type Outbound = GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2Type> = z
    .nativeEnum(GetV2ResourcesDatasetsDatasetIdRowsRowId2Type);

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowId2Type> =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema:
  z.ZodType<GetV2ResourcesDatasetsDatasetIdRowsRowId21, z.ZodTypeDef, unknown> =
    z.object({
      type: GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema,
      text: z.string(),
    });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowId21
  > = z.object({
    type: GetV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowId21$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound` instead. */
  export type Outbound = GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema),
    z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema),
  ]);

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound =
  | GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
  | GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound;

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2
  > = z.union([
    z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema),
    z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema),
      z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema),
    ])),
  ]);

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound =
  | string
  | Array<
    | GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
    | GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound
  >;

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema),
      z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdType> = z
    .nativeEnum(GetV2ResourcesDatasetsDatasetIdRowsRowIdType);

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema:
  z.ZodNativeEnum<typeof GetV2ResourcesDatasetsDatasetIdRowsRowIdType> =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdType$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: GetV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema,
    function: z.lazy(() =>
      GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema
    ),
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound = {
  id?: string | undefined;
  index?: number | undefined;
  type: string;
  function: GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: GetV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema,
    function: z.lazy(() =>
      GetV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema),
        z.lazy(() =>
          GetV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound = {
  role: string;
  content:
    | string
    | Array<
      | GetV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
      | GetV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound
    >;
  tool_calls?:
    | Array<GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound>
    | undefined;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages
  > = z.object({
    role: GetV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => GetV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema),
        z.lazy(() =>
          GetV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        GetV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound;
}

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema
      ),
    ),
    expected_output: z.nullable(z.string()).optional(),
    created: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    updated: z.string().datetime({ offset: true }).default(
      "2024-10-14T12:39:38.949Z",
    ).transform(v => new Date(v)),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound = {
  id: string;
  messages: Array<GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound>;
  expected_output?: string | null | undefined;
  created?: string | undefined;
  updated: string;
};

/** @internal */
export const GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema:
  z.ZodType<
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound,
    z.ZodTypeDef,
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        GetV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema
      ),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
    created: z.date().transform(v => v.toISOString()).optional(),
    updated: z.date().default(() => new Date("2024-10-14T12:39:38.949Z"))
      .transform(v => v.toISOString()),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$ {
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema;
  /** @deprecated use `GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound` instead. */
  export type Outbound =
    GetV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound;
}
