/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The role of the prompt message
 */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole = ClosedEnum<
  typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole
>;

export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType = {
  ImageUrl: "image_url",
} as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType =
  ClosedEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType>;

export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl = {
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId22 = {
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType;
  imageUrl: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl;
};

export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type = {
  Text: "text",
} as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type = ClosedEnum<
  typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type
>;

/**
 * Text content part of a prompt message
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId21 = {
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type;
  text: string;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2 =
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId21
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId22;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent =
  | string
  | Array<
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId21
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId22
  >;

export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdType = {
  Function: "function",
} as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdType = ClosedEnum<
  typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdType
>;

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowIdType;
  function: PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages = {
  /**
   * The role of the prompt message
   */
  role: PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId21
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId22
    >;
  toolCalls?:
    | Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls>
    | undefined;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody = {
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest = {
  /**
   * Dataset ID
   */
  datasetId: string;
  /**
   * Dataset row ID
   */
  rowId: string;
  requestBody?:
    | PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody
    | undefined;
};

/**
 * The role of the prompt message
 */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole =
  ClosedEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole>;

export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType =
  {
    ImageUrl: "image_url",
  } as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType =
  ClosedEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType
  >;

export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl = {
  /**
   * The orq.ai id of the image
   */
  id?: string | undefined;
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2 = {
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType;
  imageUrl: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl;
};

export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType = {
  Text: "text",
} as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType =
  ClosedEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType
  >;

/**
 * Text content part of a prompt message
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1 = {
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType;
  text: string;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2 =
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent =
  | string
  | Array<
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2
  >;

export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType = {
  Function: "function",
} as const;
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType =
  ClosedEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType>;

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType;
  function: PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction;
};

export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages = {
  /**
   * The role of the prompt message
   */
  role: PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2
    >;
  toolCalls?:
    | Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls>
    | undefined;
};

/**
 * Dataset updated.
 */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody = {
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole> = z
    .nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole> =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType
  > = z.nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType
  > = PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound = {
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId22,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$inboundSchema,
    image_url: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound = {
  type: string;
  image_url: PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$Outbound;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId22
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesType$outboundSchema,
    imageUrl: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId22$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound` instead. */
  export type Outbound = PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type> = z
    .nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type> =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId21,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$inboundSchema,
    text: z.string(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId21
  > = z.object({
    type: PatchV2ResourcesDatasetsDatasetIdRowsRowId2Type$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId21$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound` instead. */
  export type Outbound = PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema),
    z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema),
  ]);

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound =
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound;

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2
  > = z.union([
    z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema),
    z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent2$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema),
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema
      ),
    ])),
  ]);

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound =
  | string
  | Array<
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound
  >;

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema),
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema
      ),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContent$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdType> = z
    .nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowIdType);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema:
  z.ZodNativeEnum<typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdType> =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$inboundSchema,
    function: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$inboundSchema
    ),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound = {
  id?: string | undefined;
  index?: number | undefined;
  type: string;
  function: PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$Outbound;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PatchV2ResourcesDatasetsDatasetIdRowsRowIdType$outboundSchema,
    function: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId21$inboundSchema
        ),
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId22$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound = {
  role: string;
  content:
    | string
    | Array<
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId21$Outbound
      | PatchV2ResourcesDatasetsDatasetIdRowsRowId22$Outbound
    >;
  tool_calls?:
    | Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$Outbound>
    | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages
  > = z.object({
    role: PatchV2ResourcesDatasetsDatasetIdRowsRowIdRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId21$outboundSchema
        ),
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId22$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    messages: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$inboundSchema
      ),
    ),
    expected_output: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$Outbound = {
  messages: Array<PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$Outbound>;
  expected_output?: string | null | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody
  > = z.object({
    messages: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdMessages$outboundSchema
      ),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dataset_id: z.string(),
    row_id: z.string(),
    RequestBody: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "dataset_id": "datasetId",
      "row_id": "rowId",
      "RequestBody": "requestBody",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound = {
  dataset_id: string;
  row_id: string;
  RequestBody?:
    | PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$Outbound
    | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest
  > = z.object({
    datasetId: z.string(),
    rowId: z.string(),
    requestBody: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequestBody$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      rowId: "row_id",
      requestBody: "RequestBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdRequest$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$inboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole
  > = z.nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$outboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole
  > = PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$inboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType
  > = z.nativeEnum(
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType,
  );

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$outboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType
  > =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$Outbound =
  {
    id?: string | undefined;
    url: string;
    detail?: string | undefined;
  };

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$inboundSchema,
    image_url: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound = {
  type: string;
  image_url:
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$Outbound;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicResponseType$outboundSchema,
    imageUrl: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$inboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType
  > = z.nativeEnum(
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType,
  );

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$outboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType
  > =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$inboundSchema,
    text: z.string(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1
  > = z.object({
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2ResourcesPublicType$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema
    ),
    z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema
    ),
  ]);

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$Outbound =
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound
  | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound;

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2
  > = z.union([
    z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema
    ),
    z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema
    ),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdContentResources2$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema
      ),
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema
      ),
    ])),
  ]);

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$Outbound =
  | string
  | Array<
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound
    | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound
  >;

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema
      ),
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema
      ),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesContent$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$inboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType
  > = z.nativeEnum(PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType);

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$outboundSchema:
  z.ZodNativeEnum<
    typeof PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType
  > = PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$outboundSchema;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$Outbound =
  {
    name: string;
    arguments: string;
  };

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$inboundSchema,
    function: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$inboundSchema
    ),
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$Outbound =
  {
    id?: string | undefined;
    index?: number | undefined;
    type: string;
    function:
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$Outbound;
  };

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type:
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesType$outboundSchema,
    function: z.lazy(() =>
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$inboundSchema
        ),
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$Outbound =
  {
    role: string;
    content:
      | string
      | Array<
        | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$Outbound
        | PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$Outbound
      >;
    tool_calls?:
      | Array<
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$Outbound
      >
      | undefined;
  };

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages
  > = z.object({
    role:
      PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources1$outboundSchema
        ),
        z.lazy(() =>
          PatchV2ResourcesDatasetsDatasetIdRowsRowId2Resources2$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$Outbound;
}

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    messages: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$inboundSchema
      ),
    ),
    expected_output: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound = {
  messages: Array<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$Outbound
  >;
  expected_output?: string | null | undefined;
};

/** @internal */
export const PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema:
  z.ZodType<
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound,
    z.ZodTypeDef,
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody
  > = z.object({
    messages: z.array(
      z.lazy(() =>
        PatchV2ResourcesDatasetsDatasetIdRowsRowIdResourcesMessages$outboundSchema
      ),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$ {
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$inboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$outboundSchema;
  /** @deprecated use `PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound` instead. */
  export type Outbound =
    PatchV2ResourcesDatasetsDatasetIdRowsRowIdResponseBody$Outbound;
}
