/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The role of the prompt message
 */
export const PostV2ResourcesDatasetsDatasetIdRowsRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsRole = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsRole
>;

export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesType = {
  ImageUrl: "image_url",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRows2ResourcesType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesType
>;

export type PostV2ResourcesDatasetsDatasetIdRows2ImageUrl = {
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PostV2ResourcesDatasetsDatasetIdRows22 = {
  type: PostV2ResourcesDatasetsDatasetIdRows2ResourcesType;
  imageUrl: PostV2ResourcesDatasetsDatasetIdRows2ImageUrl;
};

export const PostV2ResourcesDatasetsDatasetIdRows2Type = {
  Text: "text",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRows2Type = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRows2Type
>;

/**
 * Text content part of a prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRows21 = {
  type: PostV2ResourcesDatasetsDatasetIdRows2Type;
  text: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsContent2 =
  | PostV2ResourcesDatasetsDatasetIdRows21
  | PostV2ResourcesDatasetsDatasetIdRows22;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsContent =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRows21
    | PostV2ResourcesDatasetsDatasetIdRows22
  >;

export const PostV2ResourcesDatasetsDatasetIdRowsType = {
  Function: "function",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsType
>;

export type PostV2ResourcesDatasetsDatasetIdRowsFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PostV2ResourcesDatasetsDatasetIdRowsType;
  function: PostV2ResourcesDatasetsDatasetIdRowsFunction;
};

export type PostV2ResourcesDatasetsDatasetIdRowsMessages = {
  /**
   * The role of the prompt message
   */
  role: PostV2ResourcesDatasetsDatasetIdRowsRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRows21
      | PostV2ResourcesDatasetsDatasetIdRows22
    >;
  toolCalls?: Array<PostV2ResourcesDatasetsDatasetIdRowsToolCalls> | undefined;
};

export type PostV2ResourcesDatasetsDatasetIdRowsRequestBody = {
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

export type PostV2ResourcesDatasetsDatasetIdRowsRequest = {
  /**
   * Dataset ID
   */
  datasetId: string;
  requestBody?: PostV2ResourcesDatasetsDatasetIdRowsRequestBody | undefined;
};

/**
 * The role of the prompt message
 */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesRole = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesRole
>;

export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType =
  {
    ImageUrl: "image_url",
  } as const;
export type PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType =
  ClosedEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType
  >;

export type PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl = {
  /**
   * The orq.ai id of the image
   */
  id?: string | undefined;
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PostV2ResourcesDatasetsDatasetIdRows2Resources2 = {
  type: PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType;
  imageUrl: PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl;
};

export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType = {
  Text: "text",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType =
  ClosedEnum<typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType>;

/**
 * Text content part of a prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRows2Resources1 = {
  type: PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType;
  text: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsContentResources2 =
  | PostV2ResourcesDatasetsDatasetIdRows2Resources1
  | PostV2ResourcesDatasetsDatasetIdRows2Resources2;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesContent =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRows2Resources1
    | PostV2ResourcesDatasetsDatasetIdRows2Resources2
  >;

export const PostV2ResourcesDatasetsDatasetIdRowsResourcesType = {
  Function: "function",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesType
>;

export type PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PostV2ResourcesDatasetsDatasetIdRowsResourcesType;
  function: PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction;
};

export type PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages = {
  /**
   * The role of the prompt message
   */
  role: PostV2ResourcesDatasetsDatasetIdRowsResourcesRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRows2Resources1
      | PostV2ResourcesDatasetsDatasetIdRows2Resources2
    >;
  toolCalls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls>
    | undefined;
};

/**
 * Expected dataset row model when talking to the API.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsResponseBody = {
  /**
   * The id of the resource
   */
  id: string;
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRole$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsRole> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsRole);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRole$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsRole> =
    PostV2ResourcesDatasetsDatasetIdRowsRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsRole$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRole$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRole$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRole$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRole$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesType> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRows2ResourcesType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesType> =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$Outbound = {
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema: z.ZodType<
  PostV2ResourcesDatasetsDatasetIdRows22,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$inboundSchema,
  image_url: z.lazy(() =>
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "image_url": "imageUrl",
  });
});

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows22$Outbound = {
  type: string;
  image_url: PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema: z.ZodType<
  PostV2ResourcesDatasetsDatasetIdRows22$Outbound,
  z.ZodTypeDef,
  PostV2ResourcesDatasetsDatasetIdRows22
> = z.object({
  type: PostV2ResourcesDatasetsDatasetIdRows2ResourcesType$outboundSchema,
  imageUrl: z.lazy(() =>
    PostV2ResourcesDatasetsDatasetIdRows2ImageUrl$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    imageUrl: "image_url",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows22$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows22$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRows22$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Type$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRows2Type> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRows2Type);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Type$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRows2Type> =
    PostV2ResourcesDatasetsDatasetIdRows2Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2Type$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Type$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Type$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Type$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Type$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema: z.ZodType<
  PostV2ResourcesDatasetsDatasetIdRows21,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: PostV2ResourcesDatasetsDatasetIdRows2Type$inboundSchema,
  text: z.string(),
});

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows21$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema: z.ZodType<
  PostV2ResourcesDatasetsDatasetIdRows21$Outbound,
  z.ZodTypeDef,
  PostV2ResourcesDatasetsDatasetIdRows21
> = z.object({
  type: PostV2ResourcesDatasetsDatasetIdRows2Type$outboundSchema,
  text: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows21$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows21$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRows21$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContent2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContent2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema),
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsContent2$Outbound =
  | PostV2ResourcesDatasetsDatasetIdRows21$Outbound
  | PostV2ResourcesDatasetsDatasetIdRows22$Outbound;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContent2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContent2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsContent2
  > = z.union([
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema),
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsContent2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContent2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContent2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent2$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsContent2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContent$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema),
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema),
    ])),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsContent$Outbound =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRows21$Outbound
    | PostV2ResourcesDatasetsDatasetIdRows22$Outbound
  >;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContent$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContent$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema),
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsContent$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContent$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContent$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContent$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsContent$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsType$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsType> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsType> =
    PostV2ResourcesDatasetsDatasetIdRowsType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsFunction$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsFunction$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsFunction$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsFunction$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsFunction$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsFunction$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsFunction$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsFunction$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsFunction$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsFunction$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsToolCalls$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsType$inboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsFunction$inboundSchema
    ),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsToolCalls$Outbound = {
  id?: string | undefined;
  index?: number | undefined;
  type: string;
  function: PostV2ResourcesDatasetsDatasetIdRowsFunction$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsToolCalls$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsToolCalls$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsType$outboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsToolCalls$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsToolCalls$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsToolCalls$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsToolCalls$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsToolCalls$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsMessages$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$inboundSchema),
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$inboundSchema),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsToolCalls$inboundSchema),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsMessages$Outbound = {
  role: string;
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRows21$Outbound
      | PostV2ResourcesDatasetsDatasetIdRows22$Outbound
    >;
  tool_calls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsToolCalls$Outbound>
    | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsMessages$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsMessages$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsMessages
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows21$outboundSchema),
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows22$outboundSchema),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsMessages$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsMessages$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsMessages$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsMessages$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsMessages$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsMessages$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsMessages$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRequestBody$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    messages: z.array(
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsMessages$inboundSchema),
    ),
    expected_output: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsRequestBody$Outbound = {
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsMessages$Outbound>;
  expected_output?: string | null | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRequestBody$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody
  > = z.object({
    messages: z.array(
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsMessages$outboundSchema),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsRequestBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequestBody$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsRequestBody$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRequest$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dataset_id: z.string(),
    RequestBody: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsRequestBody$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "dataset_id": "datasetId",
      "RequestBody": "requestBody",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsRequest$Outbound = {
  dataset_id: string;
  RequestBody?:
    | PostV2ResourcesDatasetsDatasetIdRowsRequestBody$Outbound
    | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsRequest$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsRequest$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsRequest
  > = z.object({
    datasetId: z.string(),
    requestBody: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsRequestBody$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      requestBody: "RequestBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsRequest$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRequest$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsRequest$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsRequest$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsRequest$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesRole> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsResourcesRole);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesRole> =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType
  > = z.nativeEnum(
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType,
  );

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType
  > =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$Outbound = {
  id?: string | undefined;
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2Resources2,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$inboundSchema,
    image_url: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound = {
  type: string;
  image_url: PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRows2Resources2
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicResponseType$outboundSchema,
    imageUrl: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2Resources2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType
  > = z.nativeEnum(PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType
  > = PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2Resources1,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$inboundSchema,
    text: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRows2Resources1
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRows2ResourcesPublicType$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRows2Resources1$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContentResources2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema),
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsContentResources2$Outbound =
  | PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound
  | PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsContentResources2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2
  > = z.union([
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema
    ),
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema
    ),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsContentResources2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContentResources2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContentResources2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsContentResources2$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsContentResources2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema
      ),
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema
      ),
    ])),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$Outbound =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound
    | PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound
  >;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema
      ),
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema
      ),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesContent$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesType$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesType> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsResourcesType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsResourcesType> =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsResourcesType$inboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$inboundSchema
    ),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$Outbound = {
  id?: string | undefined;
  index?: number | undefined;
  type: string;
  function: PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsResourcesType$outboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsResourcesFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRows2Resources1$inboundSchema
        ),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRows2Resources2$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$Outbound = {
  role: string;
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRows2Resources1$Outbound
      | PostV2ResourcesDatasetsDatasetIdRows2Resources2$Outbound
    >;
  tool_calls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$Outbound>
    | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsResourcesRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRows2Resources1$outboundSchema
        ),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRows2Resources2$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsResourcesToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResponseBody$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$inboundSchema
      ),
    ),
    expected_output: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsResponseBody$Outbound = {
  id: string;
  messages: Array<
    PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$Outbound
  >;
  expected_output?: string | null | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsResponseBody$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsResourcesMessages$outboundSchema
      ),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsResponseBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsResponseBody$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsResponseBody$Outbound;
}
