/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";

export type PostV2ResourcesDatasetsRequestBody = {
  /**
   * Name of the dataset
   */
  displayName: string;
};

/**
 * Dataset Created.
 */
export type PostV2ResourcesDatasetsResponseBody = {
  /**
   * Name of the dataset
   */
  displayName: string;
  /**
   * Domain ID reference
   */
  domainId: string;
};

/** @internal */
export const PostV2ResourcesDatasetsRequestBody$inboundSchema: z.ZodType<
  PostV2ResourcesDatasetsRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
  });
});

/** @internal */
export type PostV2ResourcesDatasetsRequestBody$Outbound = {
  display_name: string;
};

/** @internal */
export const PostV2ResourcesDatasetsRequestBody$outboundSchema: z.ZodType<
  PostV2ResourcesDatasetsRequestBody$Outbound,
  z.ZodTypeDef,
  PostV2ResourcesDatasetsRequestBody
> = z.object({
  displayName: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsRequestBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostV2ResourcesDatasetsRequestBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsRequestBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsRequestBody$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsRequestBody$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsResponseBody$inboundSchema: z.ZodType<
  PostV2ResourcesDatasetsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_name: z.string(),
  domain_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "display_name": "displayName",
    "domain_id": "domainId",
  });
});

/** @internal */
export type PostV2ResourcesDatasetsResponseBody$Outbound = {
  display_name: string;
  domain_id: string;
};

/** @internal */
export const PostV2ResourcesDatasetsResponseBody$outboundSchema: z.ZodType<
  PostV2ResourcesDatasetsResponseBody$Outbound,
  z.ZodTypeDef,
  PostV2ResourcesDatasetsResponseBody
> = z.object({
  displayName: z.string(),
  domainId: z.string(),
}).transform((v) => {
  return remap$(v, {
    displayName: "display_name",
    domainId: "domain_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsResponseBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsResponseBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsResponseBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsResponseBody$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsResponseBody$Outbound;
}
