/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The role of the prompt message
 */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkRole = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulkRole
>;

export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType = {
  ImageUrl: "image_url",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType
>;

export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl = {
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk22 = {
  type: PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType;
  imageUrl: PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl;
};

export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Type = {
  Text: "text",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2Type = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2Type
>;

/**
 * Text content part of a prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk21 = {
  type: PostV2ResourcesDatasetsDatasetIdRowsBulk2Type;
  text: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkContent2 =
  | PostV2ResourcesDatasetsDatasetIdRowsBulk21
  | PostV2ResourcesDatasetsDatasetIdRowsBulk22;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkContent =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRowsBulk21
    | PostV2ResourcesDatasetsDatasetIdRowsBulk22
  >;

export const PostV2ResourcesDatasetsDatasetIdRowsBulkType = {
  Function: "function",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulkType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulkType
>;

export type PostV2ResourcesDatasetsDatasetIdRowsBulkFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PostV2ResourcesDatasetsDatasetIdRowsBulkType;
  function: PostV2ResourcesDatasetsDatasetIdRowsBulkFunction;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkMessages = {
  /**
   * The role of the prompt message
   */
  role: PostV2ResourcesDatasetsDatasetIdRowsBulkRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRowsBulk21
      | PostV2ResourcesDatasetsDatasetIdRowsBulk22
    >;
  toolCalls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls>
    | undefined;
};

/**
 * Expected dataset row model when talking to the API.
 */
export type DatasetRows = {
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsBulkMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody = {
  datasetRows: Array<DatasetRows>;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkRequest = {
  /**
   * Dataset ID
   */
  datasetId: string;
  requestBody?: PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody | undefined;
};

/**
 * The role of the prompt message
 */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole = {
  System: "system",
  Assistant: "assistant",
  User: "user",
  Exception: "exception",
  Tool: "tool",
  Prompt: "prompt",
  Correction: "correction",
  ExpectedOutput: "expected_output",
} as const;
/**
 * The role of the prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole
>;

export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType =
  {
    ImageUrl: "image_url",
  } as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType =
  ClosedEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType
  >;

export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl = {
  /**
   * The orq.ai id of the image
   */
  id?: string | undefined;
  /**
   * Either a URL of the image or the base64 encoded data URI.
   */
  url: string;
  /**
   * Specifies the detail level of the image. Currently only supported with OpenAI models
   */
  detail?: string | undefined;
};

/**
 * The image part of the prompt message. Only supported with vision models.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2 = {
  type: PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType;
  imageUrl: PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl;
};

export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType = {
  Text: "text",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType =
  ClosedEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType
  >;

/**
 * Text content part of a prompt message
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1 = {
  type: PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType;
  text: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2 =
  | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1
  | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2;

/**
 * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1
    | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2
  >;

export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType = {
  Function: "function",
} as const;
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType = ClosedEnum<
  typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType
>;

export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction = {
  name: string;
  /**
   * JSON string arguments for the functions
   */
  arguments: string;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls = {
  id?: string | undefined;
  index?: number | undefined;
  type: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType;
  function: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction;
};

export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages = {
  /**
   * The role of the prompt message
   */
  role: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole;
  /**
   * The contents of the user message. Either the text content of the message or an array of content parts with a defined type, each can be of type `text` or `image_url` when passing in images. You can pass multiple images by adding multiple `image_url` content parts.
   */
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1
      | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2
    >;
  toolCalls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls>
    | undefined;
};

/**
 * Expected dataset row model when talking to the API.
 */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody = {
  /**
   * The id of the resource
   */
  id: string;
  /**
   * Input message(s) of the dataset row
   */
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages>;
  /**
   * Reference of the dataset row
   */
  expectedOutput?: string | null | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRole$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulkRole> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulkRole);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRole$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulkRole> =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkRole$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRole$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRole$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRole$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRole$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType
  > = z.nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType
  > = PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$Outbound = {
  url: string;
  detail?: string | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl
  > = z.object({
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema:
  z.ZodType<PostV2ResourcesDatasetsDatasetIdRowsBulk22, z.ZodTypeDef, unknown> =
    z.object({
      type:
        PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$inboundSchema,
      image_url: z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$inboundSchema
      ),
    }).transform((v) => {
      return remap$(v, {
        "image_url": "imageUrl",
      });
    });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound = {
  type: string;
  image_url: PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk22
  > = z.object({
    type: PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesType$outboundSchema,
    imageUrl: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk22$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2Type> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulk2Type);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2Type> =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema:
  z.ZodType<PostV2ResourcesDatasetsDatasetIdRowsBulk21, z.ZodTypeDef, unknown> =
    z.object({
      type: PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$inboundSchema,
      text: z.string(),
    });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk21
  > = z.object({
    type: PostV2ResourcesDatasetsDatasetIdRowsBulk2Type$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk21$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound` instead. */
  export type Outbound = PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema),
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$Outbound =
  | PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound
  | PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2
  > = z.union([
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema),
    z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContent$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema),
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema),
    ])),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkContent$Outbound =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound
    | PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound
  >;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContent$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema),
      z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkContent$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContent$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContent$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkType$inboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulkType> = z
    .nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulkType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkType$outboundSchema:
  z.ZodNativeEnum<typeof PostV2ResourcesDatasetsDatasetIdRowsBulkType> =
    PostV2ResourcesDatasetsDatasetIdRowsBulkType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$Outbound = {
  name: string;
  arguments: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsBulkType$inboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$inboundSchema
    ),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$Outbound = {
  id?: string | undefined;
  index?: number | undefined;
  type: string;
  function: PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsBulkType$outboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsBulkRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$inboundSchema),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk22$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$Outbound = {
  role: string;
  content:
    | string
    | Array<
      | PostV2ResourcesDatasetsDatasetIdRowsBulk21$Outbound
      | PostV2ResourcesDatasetsDatasetIdRowsBulk22$Outbound
    >;
  tool_calls?:
    | Array<PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$Outbound>
    | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsBulkRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() => PostV2ResourcesDatasetsDatasetIdRowsBulk21$outboundSchema),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk22$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$Outbound;
}

/** @internal */
export const DatasetRows$inboundSchema: z.ZodType<
  DatasetRows,
  z.ZodTypeDef,
  unknown
> = z.object({
  messages: z.array(
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$inboundSchema
    ),
  ),
  expected_output: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "expected_output": "expectedOutput",
  });
});

/** @internal */
export type DatasetRows$Outbound = {
  messages: Array<PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$Outbound>;
  expected_output?: string | null | undefined;
};

/** @internal */
export const DatasetRows$outboundSchema: z.ZodType<
  DatasetRows$Outbound,
  z.ZodTypeDef,
  DatasetRows
> = z.object({
  messages: z.array(
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkMessages$outboundSchema
    ),
  ),
  expectedOutput: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    expectedOutput: "expected_output",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DatasetRows$ {
  /** @deprecated use `DatasetRows$inboundSchema` instead. */
  export const inboundSchema = DatasetRows$inboundSchema;
  /** @deprecated use `DatasetRows$outboundSchema` instead. */
  export const outboundSchema = DatasetRows$outboundSchema;
  /** @deprecated use `DatasetRows$Outbound` instead. */
  export type Outbound = DatasetRows$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    datasetRows: z.array(z.lazy(() => DatasetRows$inboundSchema)),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$Outbound = {
  datasetRows: Array<DatasetRows$Outbound>;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody
  > = z.object({
    datasetRows: z.array(z.lazy(() => DatasetRows$outboundSchema)),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    dataset_id: z.string(),
    RequestBody: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$inboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "dataset_id": "datasetId",
      "RequestBody": "requestBody",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$Outbound = {
  dataset_id: string;
  RequestBody?:
    | PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$Outbound
    | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest
  > = z.object({
    datasetId: z.string(),
    requestBody: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkRequestBody$outboundSchema
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      datasetId: "dataset_id",
      requestBody: "RequestBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkRequest$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole
  > = z.nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole
  > = PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType
  > = z.nativeEnum(
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType,
  );

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType
  > =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$Outbound =
  {
    id?: string | undefined;
    url: string;
    detail?: string | undefined;
  };

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl
  > = z.object({
    id: z.string().optional(),
    url: z.string(),
    detail: z.string().optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$inboundSchema,
    image_url: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "image_url": "imageUrl",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound = {
  type: string;
  image_url:
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$Outbound;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicResponseType$outboundSchema,
    imageUrl: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesImageUrl$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      imageUrl: "image_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType
  > = z.nativeEnum(
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType,
  );

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType
  > =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1,
    z.ZodTypeDef,
    unknown
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$inboundSchema,
    text: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound = {
  type: string;
  text: string;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1
  > = z.object({
    type:
      PostV2ResourcesDatasetsDatasetIdRowsBulk2ResourcesPublicType$outboundSchema,
    text: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema
    ),
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema
    ),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$Outbound =
  | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound
  | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2
  > = z.union([
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema
    ),
    z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema
    ),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkContentResources2$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent,
    z.ZodTypeDef,
    unknown
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema
      ),
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema
      ),
    ])),
  ]);

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$Outbound =
  | string
  | Array<
    | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound
    | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound
  >;

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent
  > = z.union([
    z.string(),
    z.array(z.union([
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema
      ),
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema
      ),
    ])),
  ]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesContent$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$inboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType
  > = z.nativeEnum(PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType);

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$outboundSchema:
  z.ZodNativeEnum<
    typeof PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType
  > = PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$outboundSchema;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$Outbound =
  {
    name: string;
    arguments: string;
  };

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction
  > = z.object({
    name: z.string(),
    arguments: z.string(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$inboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$inboundSchema
    ),
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$Outbound =
  {
    id?: string | undefined;
    index?: number | undefined;
    type: string;
    function:
      PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$Outbound;
  };

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls
  > = z.object({
    id: z.string().optional(),
    index: z.number().optional(),
    type: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesType$outboundSchema,
    function: z.lazy(() =>
      PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesFunction$outboundSchema
    ),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages,
    z.ZodTypeDef,
    unknown
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$inboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$inboundSchema
        ),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$inboundSchema
        ),
      ])),
    ]),
    tool_calls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$inboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      "tool_calls": "toolCalls",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$Outbound =
  {
    role: string;
    content:
      | string
      | Array<
        | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$Outbound
        | PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$Outbound
      >;
    tool_calls?:
      | Array<
        PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$Outbound
      >
      | undefined;
  };

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages
  > = z.object({
    role: PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesRole$outboundSchema,
    content: z.union([
      z.string(),
      z.array(z.union([
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources1$outboundSchema
        ),
        z.lazy(() =>
          PostV2ResourcesDatasetsDatasetIdRowsBulk2Resources2$outboundSchema
        ),
      ])),
    ]),
    toolCalls: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesToolCalls$outboundSchema
      ),
    ).optional(),
  }).transform((v) => {
    return remap$(v, {
      toolCalls: "tool_calls",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$Outbound;
}

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$inboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$inboundSchema
      ),
    ),
    expected_output: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "expected_output": "expectedOutput",
    });
  });

/** @internal */
export type PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$Outbound = {
  id: string;
  messages: Array<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$Outbound
  >;
  expected_output?: string | null | undefined;
};

/** @internal */
export const PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$outboundSchema:
  z.ZodType<
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$Outbound,
    z.ZodTypeDef,
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody
  > = z.object({
    id: z.string(),
    messages: z.array(
      z.lazy(() =>
        PostV2ResourcesDatasetsDatasetIdRowsBulkResourcesMessages$outboundSchema
      ),
    ),
    expectedOutput: z.nullable(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      expectedOutput: "expected_output",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$ {
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$inboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$outboundSchema;
  /** @deprecated use `PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$Outbound` instead. */
  export type Outbound =
    PostV2ResourcesDatasetsDatasetIdRowsBulkResponseBody$Outbound;
}
