name: '[Pre-release] Publishing openapi schema'

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+' # v1.0.0-rc.1
    paths:
      - .openapi/openapi.json
      - .openapi/openapi-overlay-prerelease.yaml
    # branches:
    #   - feat/ORQ-6625-github-workflow-to-publish-sdk-openapi-schema

jobs:
  publish:
    uses: ./.github/workflows/publish-openapi-schema.yml
    name: Runner
    secrets: inherit
    with:
      generated_openapi_schema_name: openapi-prerelease.yaml
