name: Generate
permissions:
  contents: write
on:
  push:
    branches:
      - main
    # paths:
    #   - .speakeasy/gen.yaml
jobs:
  get_target:
    runs-on: ubuntu-latest
    outputs:
      target: ${{ steps.target.outputs.target }}
    name: Get sdk release target
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install yaml parser
        uses: chrisdickinson/setup-yq@latest

      - name: Get sdk target base from the version set
        id: target
        shell: bash
        run: |
          SDK_TARGET_VERSION=$(yq r .speakeasy/gen.yaml '.typescript.version')
          echo $SDK_TARGET_VERSION
          echo "$SDK_TARGET_VERSION" | grep -q "-rc"
          if [[ $? -eq 0 ]] ; then
            echo "target=orq-prerelease" >> "$GITHUB_OUTPUT"
          else
            echo "target=orq" >> "$GITHUB_OUTPUT"
          fi
  generate:
    needs: get_target
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      mode: direct
      target: ${{ needs.get_target.outputs.target }}
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}