name: Generate
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
"on":
  workflow_dispatch:
    # inputs:
    #   force:
    #     description: Force generation of SDKs
    #     type: boolean
    #     default: false
    #   set_version:
    #     description: optionally set a specific SDK version
    #     type: string
  # push:
  #   paths:
  #     - .speakeasy/gen.yaml
  # schedule:
  #   - cron: 0 0 * * *
jobs:
  # generate:
  #   runs-on: ubuntu-latest
  #   name: Setup speakeasy
  #   env:
  #     SPEAKEASY_API_KEY: ${{ secrets.SPEAKEASY_API_KEY }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Install speakeasy cli
  #       run: curl -fsSL https://raw.githubusercontent.com/speakeasy-api/speakeasy/main/install.sh | sh

  #     - name: Verify
  #       run: speakeasy --version

  #     - name: Generate
  #       run: speakeasy run
  publish:
    needs: generate
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: orq
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
    # uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    # with:
    #   force: ${{ github.event.inputs.force }}
    #   mode: pr
    #   set_version: ${{ github.event.inputs.set_version }}
    # secrets:
    #   github_access_token: ${{ secrets.GITHUB_TOKEN }}
    #   npm_token: ${{ secrets.NPM_TOKEN }}
    #   speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}